name: 'Setup Host'
description: 'Configures the host runner to run the build'

inputs:
  gradle-encryption-key:
    description: 'The encryption key to use for the Gradle Configuration cache'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup JDK17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}
        cache-read-only: false
        build-scan-publish: true
        build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
        build-scan-terms-of-use-agree: 'yes'
    - name: Add Android SDK to PATH
      shell: bash
      run: |
        echo "ANDROID_HOME=$ANDROID_HOME" >> "$GITHUB_ENV"
        echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools" >> "$GITHUB_PATH"
    - name: Accept Android licences
      shell: bash
      run: yes | sdkmanager --licenses || true
    - name: Enable Hardware Acceleration
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
