name: 'Setup Host'
description: 'Configures the host runner to run the build'

inputs:
  gradle-encryption-key:
    description: 'The encryption key to use for the Gradle Configuration cache'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup JDK17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}
    - name: Accept Android licences
      shell: bash
      run: (yes || true) | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
    - # https://developer.android.com/studio/test/gradle-managed-devices#create_a_gradle_managed_device
      name: Set `swiftshader_indirect` on Android Emulators (required by GHA)
      shell: bash
      run: echo "android.testoptions.manageddevices.emulator.gpu=swiftshader_indirect" >> ~/.gradle/gradle.properties
